# This is the input file for playbook_overlay_delete_preview.yml and playbook_overlay_delete_commit.yml
# If there are multiple VRFs or Vlans in the overlay_db.yml and if you want to delete only selective
# ones or all of them, then declare the respective VRFs/Vlan under their section as shown below 
#
# List the VRFs to be removed under 'vrfs' keyword
# List the Vlans to be removed under 'vlans' keyword
#
#The keyword 'update_access' when set to true deletes the related VLANs from the interfaces
# ______________________________________________
# __________ EXAMPLE SCENARIOS _________________
# ______________________________________________
#
# Example-1: deletes blue and green vrfs and vlan 101 and 102
# 
#   vrfs:
#      - blue             <--------- deletes blue and green vrfs
#      - green
#   vlans:
#      - 101             <--------- deletes vlan 102 and 102
#      - 102
#
#   update_access: true   <--------- deletes the respective VLANs from the access interfaces
#
# Example-2: deletes all the vrfs and all vlans which are not provisioned in the device 
#
#   vrfs:
#      - all            <--------- deletes all vrfs which are not provisioned in the device
#
#   vlans:
#      - all             <--------- deletes all vlans which are not provisioned in the device
# 
#   update_access: false   <--------- makes NO changes to the access interfaces           
# ______________________________________________
# ______________________________________________
# ______________________________________________

vrfs:
   - all

vlans:
   - all

update_access: true

