---
- name: Overlay "group_vars/overlay_db.yml" validation
  hosts: all
  gather_facts: false
  tasks:
    - name: Collect vars from underlay_db.yml # noqa: run-once[task]
      run_once: true
      ansible.builtin.include_vars:
        file: ../group_vars/underlay_db.yml
        name: underlay_db

    - name: Collect vars from overlay_db.yml # noqa: run-once[task]
      run_once: true
      ansible.builtin.include_vars:
        file: ../group_vars/overlay_db.yml
        name: overlay_db

    - name: Process data
      precheck_yml:
        underlay_db: "{{ underlay_db }}"
        overlay_db: "{{ overlay_db }}"
      register: result

    - name: Print result # noqa: run-once[task]
      run_once: true
      ansible.builtin.debug:
        msg: "Yaml file validation : {{ result }}'"
