hostname: 'LEAF-2'

underlay_interfaces:
  Loopback0:
    description: 'ROUTER-ID'
    ip_address: '192.168.210.12'
    subnet_mask: '255.255.255.255'
    type: 'loopback'

  Loopback1:
    description: 'VTEP'
    ip_address: '192.168.211.12'
    subnet_mask: '255.255.255.255'
    type: 'loopback'

  GigabitEthernet1/0/24:
    description: 'UNDERLAY-FABRIC'

#layer 3 interface
overlay_interfaces:
  Loopback100:
    description: 'UNIQUE-LOOPBACK-VRF-TEST'
    ip_address: '10.1.10.12'
    subnet_mask: '255.255.255.255'
    type: 'loopback'
    vrf: 'test'

  Loopback101:
    description: 'UNIQUE-LOOPBACK-VRF-TEST2'
    ip_address: '10.1.11.12'
    subnet_mask: '255.255.255.255'
    type: 'loopback'
    vrf: 'test2'

  GigabitEthernet1/0/1:
    description: 'Link to Router1-1/0'
    type: 'tagged'

  GigabitEthernet1/0/1.100:
    description: 'test'
    type: 'subintf'
    dot1q: '100'
    ip_address: '10.1.31.12'
    subnet_mask: '255.255.255.255'
    vrf: 'test'