hostname: 'LEAF-1'

underlay_interfaces:
  Loopback0:
    description: 'ROUTER-ID'
    ip_address: '192.168.210.11'
    subnet_mask: '255.255.255.255'
    type: 'loopback'

  Loopback1:
    description: 'VTEP'
    ip_address: '192.168.211.11'
    subnet_mask: '255.255.255.255'
    type: 'loopback'

  GigabitEthernet1/0/24:
    description: 'UNDERLAY-FABRIC'

#layer 3 interface
overlay_interfaces:
  Loopback100:
    description: 'UNIQUE-LOOPBACK-VRF-TEST'
    ip_address: '10.1.10.11'
    subnet_mask: '255.255.255.255'
    loopback: 'yes'
    vrf: 'test'

  Loopback101:
    description: 'UNIQUE-LOOPBACK-VRF-TEST2'
    ip_address: '10.1.11.11'
    subnet_mask: '255.255.255.255'
    loopback: 'yes'
    vrf: 'test2'

  GigabitEthernet1/0/1:
    description: 'Link to Router1-1/0'
    type: 'slave'
    etherchannel_number: '10'

  GigabitEthernet1/0/2:
    description: 'Link to Router1-1/1'
    type: 'slave'
    etherchannel_number: '10'

  Port-channel1:
    description: 'Link to Router1'
    type: 'master'
    ip_address: '10.1.21.11'
    subnet_mask: '255.255.255.255'
    vrf: 'test2'