---

- name: Overlay "group_vars/overlay_db.yml" validation 
  hosts: all 
  gather_facts: false
  tasks:  
          - name: Collect vars from underlay_db.yml
            run_once: true
            include_vars:
              file: ../group_vars/underlay_db.yml
              name: underlay_db

          - name: Collect vars from overlay_db.yml
            run_once: true
            include_vars:
              file: ../group_vars/overlay_db.yml
              name: overlay_db

          - name: Process data
            precheck_yml:
              underlay_db: "{{ underlay_db }}"
              overlay_db: "{{ overlay_db }}"
              #debug : 'verbose'( displaying complete output if validation is successful else displays the errors)
              #debug : ' '(displays only error senarios if found any)
              debug : ''
            register: result
            
          - name: Print result
            run_once: true
            debug:
              msg: "Yaml file validation : {{ result}}'"
