---

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: all
  gather_facts: false
  vars:
    overlay_block: ""
    leaf_ol_dict:
      './templates/vrf_definition.j2': 'vrf definition block'
      './templates/bgp_l2vpn_ipv46_per_vrf.j2': 'bgp per vrf block'
      './templates/vrf_evi_vni_vlan_stiching.j2': 'vrf evi vni vlan stiching block'
      './templates/vrf_nve_vni_assign.j2': 'vrf nve vni assign block'
      './templates/vrf_svi_create.j2': 'vrf svi create block'
      './templates/vlan_create.j2': 'vlan block'
      './templates/svi_create.j2': 'svi block'
      './templates/evi_vni_vlan_stiching.j2': 'evi vni vlan stiching block'
      './templates/overlay_interfaces.j2': 'overlay interface block'
      './templates/nve_vni_assign.j2': 'nve block'

  tasks:
    # Set db file path and load overlay_db
    - name: Load and process overlay input file # noqa: run-once[task]
      run_once: true
      block:
        - name: Set overlay db input file path if not already set
          when: input_vars_path is not defined
          ansible.builtin.set_fact:
            input_vars_path: "../"

        - name: Load vars from overlay input file
          ansible.builtin.include_vars:
            file: "{{ input_vars_path }}group_vars/overlay_db.yml"

        - name: Load vars from underlay input file
          ansible.builtin.include_vars:
            file: "{{ input_vars_path }}group_vars/underlay_db.yml"

    - name: Load vars from node_vars/<host>.yml input file
      ansible.builtin.include_vars:
        file: "{{ input_vars_path }}host_vars/node_vars/{{ inventory_hostname }}.yml"

    - name: Read template files
      when: inventory_hostname in groups['leaf']
      ansible.builtin.set_fact:
        overlay_block: "{{ overlay_block }} ! {{ leaf_ol_dict[item.key] }} {{ lookup('template', item.key) }}"
      with_dict: "{{ leaf_ol_dict }}"


    - name: Render template files output
      ansible.builtin.set_fact:
        rendered: "{{  overlay_block | regex_replace('#jinja2: lstrip_blocks: \"True\", trim_blocks: \"True\"', '') | regex_replace('\\n(\\s+)','\n') | regex_replace('! ','\n\n! ') }}"

    - name: Copy configurations to respective file ( <hostname>-overlay.txt ) under 'preview_files' folder
      ansible.builtin.copy:
        mode: preserve
        dest: preview_files/{{ inventory_hostname }}-overlay.txt
        content: "{{ rendered }}"

- name: Display output file info
  hosts: localhost
  gather_facts: false
  run_once: true # noqa: run-once[play]

  tasks:
    - name: Final Output
      ansible.builtin.debug:
        msg: Please refer to <hostname>-overlay.txt in 'preview_files' folder
