---

- name: Initialising variable for leaf-s
  hosts: leaf
  gather_facts: false
  
  tasks:    
          - set_fact:
              incremental: true

- name: Initialising variable for localhost
  hosts: localhost
  gather_facts: false
  tasks:    
          - set_fact:
              incremental: true

- name: Write DAG incremental info to files in host_vars/inc_vars folder
  import_playbook: playbook_overlay_incremental_generate.yml
  
- name: Import tasks from playbook_access_add_commit.yml
  import_playbook: playbook_access_add_commit.yml
