---
- name: Collect outputs after config
  hosts: all
  gather_facts: false
  connection: network_cli
  vars_files:
    - "../group_vars/overlay_db.yml"

  tasks:
    - name: Construct show commands from host var file for leafs
      when: inventory_hostname in groups['leaf']
      ansible.builtin.copy:
        mode: '0660'
        dest: "output/{{ inventory_hostname }}-show_commands.txt"
        content: "{{ lookup('template', './templates/leaf_show_command.j2') }}"

    - name: Cat show commands file of leaf
      when: inventory_hostname in groups['leaf']
      ansible.builtin.command: cat "output/{{ inventory_hostname }}-show_commands.txt"
      register: leaf_command_buf
      changed_when: false

    - name: Rrun show command on Leafs
      when: inventory_hostname in groups['leaf']
      cisco.ios.ios_command:
        commands:
          "{{ leaf_command_buf.stdout_lines }}"
      register: leaf_output

    - name: Save outputs to output file for Leafs
      when: inventory_hostname in groups['leaf']
      ansible.builtin.copy:
        mode: '0660'
        dest: "output/{{ inventory_hostname }}-show_output.txt"
        content: |
          "{{ leaf_command_buf.stdout_lines | zip(leaf_output.stdout_lines) | to_nice_yaml }}"

    - name: Construct show commands from host var file for Spines
      when: inventory_hostname in groups['spine']
      ansible.builtin.copy:
        mode: '0660'
        dest: "output/{{ inventory_hostname }}-show_commands.txt"
        content: "{{ lookup('template', './templates/spine_show_command.j2') }}"

    - name: Cat show commands file of Spines
      when: inventory_hostname in groups['spine']
      ansible.builtin.command: cat "output/{{ inventory_hostname }}-show_commands.txt"
      register: spine_command_buf
      changed_when: false

    - name: Run show command on Spines
      when: inventory_hostname in groups['spine']
      cisco.ios.ios_command:
        commands:
          "{{ spine_command_buf.stdout_lines }}"
      register: spine_output

    - name: Save outputs to output file for Spines
      when: inventory_hostname in groups['spine']
      ansible.builtin.copy:
        mode: '0660'
        dest: "output/{{ inventory_hostname }}-show_output.txt"
        content: |
          "{{ spine_command_buf.stdout_lines | zip(spine_output.stdout_lines) | to_nice_yaml }}"

    - name: Display output file info # noqa: run-once[task]
      run_once: true
      ansible.builtin.debug:
        msg: Please refer to <hostname>-show_commands.txt  in 'output' folder

    - name: Display output file info # noqa: run-once[task]
      run_once: true
      ansible.builtin.debug:
        msg: Please refer to <hostname>-show_output.txt in 'output' folder
