---
- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: leaf
  gather_facts: false

  tasks:
    - name: Locate files in ../host_vars/inc_vars dir
      ansible.builtin.find:
        path: "../host_vars/inc_vars"
      register: cleanup
      ignore_errors: true

    - name: Remove files from previous run
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ cleanup.files }}"
      ignore_errors: true
      register: ignore_errors_register

    - name: Collect vars from incremental_vars.yml # noqa: run-once[task]
      run_once: true
      ansible.builtin.include_vars:
        file: ../group_vars/create_vars.yml
        name: user_input

#    - name: Collect vars from ../host_vars/access_intf
#      include_vars:
#        file: ../host_vars/access_intf/{{ inventory_hostname }}.yml
#        name: access_intf_input

    - name: Collect vars from overlay_db.yml # noqa: run-once[task]
      run_once: true
      ansible.builtin.include_vars:
        file: ../group_vars/overlay_db.yml
        name: to_compare

    - name: Collect vars from hostvars leafs
      ansible.builtin.include_vars:
        file: ../host_vars/node_vars/{{ inventory_hostname }}.yml
        name: hostvars_leaf_data

    - name: Collect "show run nve"
      ansible.netcommon.cli_command:
        command: show run nve
      register: command_output

#    - name: Collect "show run | sec ^int"
#      cli_command:
#        command: show run | sec ^int
#      register: sec_command_output

    - name: Process data
      create_incremental_add_yml:
        userinput: "{{ user_input }}"
#        access_input: "{{ access_intf_input }}"
        overlay_intf: "{{ hostvars_leaf_data }}"
        hostvars: "{{ command_output.stdout_lines }}"
        tocompare: "{{ to_compare }}"
#        sec_output: "{{ sec_command_output.stdout_lines }}"
      register: module_output

    - name: Copying configurations to the repective files ( <hostname>.yml ) under ../host_vars/inc_vars folder
      when: module_output['yaml'] != '{}\n'
      ansible.builtin.copy:
        mode: '0660'
        dest: ../host_vars/inc_vars/{{ inventory_hostname }}.yml
        content: "{{ module_output['yaml'] }}"
