---
- name: Overlay "group_vars/overlay_db.yml" validation
  hosts: all
  gather_facts: false
  tasks:
      # Set db file path and load overlay_db
    - name: Load and process overlay input file # noqa: run-once[task]
      run_once: true
      block:
        - name: Set overlay db input file path if not already set
          when: input_vars_path is not defined
          ansible.builtin.set_fact:
            input_vars_path: "../"

        - name: Load vars from overlay input file
          ansible.builtin.include_vars:
            file: "{{ input_vars_path }}group_vars/overlay_db.yml"
            name: overlay_db

        - name: Load vars from underlay input file
          ansible.builtin.include_vars:
            file: "{{ input_vars_path }}group_vars/underlay_db.yml"
            name: underlay_db

    - name: Process data
      precheck_yml:
        underlay_db: "{{ underlay_db }}"
        overlay_db: "{{ overlay_db }}"
      register: result

    - name: Print result # noqa: run-once[task]
      run_once: true
      ansible.builtin.debug:
        msg: "Yaml file validation : {{ result }}'"
