# .github/workflows/ansible-lint.yml
name: ansible-lint
on: [push, pull_request]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
     - name: Install Python dependencies
       run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Lint playbook
       uses: ansible/ansible-lint@main
